baseURL = "/"
languageCode = "en-us"
title = "Docdock"
theme = "docdock"
themesdir = "../.."

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false
noSearch = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


